// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/add-entrada.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared.ts
var MESES = [
  "Janeiro",
  "Fevereiro",
  "Mar\xE7o",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro"
];
function currentMes() {
  return MESES[(/* @__PURE__ */ new Date()).getMonth()];
}
function today() {
  return (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/add-entrada.ts
var add_entrada_default = defineTool({
  name: "add_entrada",
  title: "Registrar entrada",
  description: "Record a new income entry (entrada) for the signed-in user.",
  inputSchema: {
    descricao: z.string().describe("Description of the income."),
    valor: z.number().describe("Amount in BRL."),
    categoria: z.string().describe('Category, e.g. "Sal\xE1rio", "Freelance", "Investimentos", "Outros".'),
    responsavel: z.string().describe('Person responsible, e.g. "William" or "Andressa".'),
    data: z.string().optional().describe("Date as YYYY-MM-DD. Defaults to today."),
    mes: z.string().optional().describe("Month name in Portuguese. Defaults to the current month.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("entradas").insert({
      user_id: ctx.getUserId(),
      descricao: input.descricao,
      valor: input.valor,
      categoria: input.categoria,
      responsavel: input.responsavel,
      data: input.data ?? today(),
      mes: input.mes ?? currentMes()
    }).select().single();
    if (error) return fail(error.message);
    return ok({ entrada: data });
  }
});

// src/lib/mcp/tools/add-gasto.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_gasto_default = defineTool2({
  name: "add_gasto",
  title: "Registrar gasto",
  description: "Record a new expense (gasto) for the signed-in user.",
  inputSchema: {
    descricao: z2.string().describe("What the expense was for."),
    valor: z2.number().describe("Amount in BRL."),
    categoria: z2.string().describe('Category, e.g. "Alimenta\xE7\xE3o", "Transporte", "Moradia", "Outros".'),
    responsavel: z2.string().describe('Person responsible, e.g. "William" or "Andressa".'),
    data: z2.string().optional().describe("Date as YYYY-MM-DD. Defaults to today."),
    mes: z2.string().optional().describe("Month name in Portuguese. Defaults to the current month."),
    pago: z2.boolean().optional().describe("Whether it is already paid. Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("gastos").insert({
      user_id: ctx.getUserId(),
      descricao: input.descricao,
      valor: input.valor,
      categoria: input.categoria,
      responsavel: input.responsavel,
      data: input.data ?? today(),
      mes: input.mes ?? currentMes(),
      pago: input.pago ?? true
    }).select().single();
    if (error) return fail(error.message);
    return ok({ gasto: data });
  }
});

// src/lib/mcp/tools/list-contas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_contas_default = defineTool3({
  name: "list_contas",
  title: "Listar contas",
  description: "List the signed-in user's bills (contas) for a month, with paid/pending status.",
  inputSchema: {
    mes: z3.string().optional().describe("Month name in Portuguese. Defaults to the current month."),
    apenas_pendentes: z3.boolean().optional().describe("Return only unpaid bills.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mes, apenas_pendentes }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contas").select("id, conta, valor, vencimento, pago, data_pagamento, responsavel, mes").eq("mes", mes ?? currentMes()).order("vencimento", { ascending: true });
    if (apenas_pendentes) query = query.eq("pago", false);
    const { data, error } = await query;
    if (error) return fail(error.message);
    const total = (data ?? []).reduce((s, c) => s + Number(c.valor ?? 0), 0);
    const pendente = (data ?? []).filter((c) => !c.pago).reduce((s, c) => s + Number(c.valor ?? 0), 0);
    return ok({ mes: mes ?? currentMes(), count: data?.length ?? 0, total, total_pendente: pendente, contas: data ?? [] });
  }
});

// src/lib/mcp/tools/list-entradas.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_entradas_default = defineTool4({
  name: "list_entradas",
  title: "Listar entradas",
  description: "List the signed-in user's income entries (entradas) for a month.",
  inputSchema: {
    mes: z4.string().optional().describe('Month name in Portuguese, e.g. "Agosto". Defaults to the current month.'),
    responsavel: z4.string().optional().describe("Person responsible filter."),
    limit: z4.number().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mes, responsavel, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("entradas").select("id, data, descricao, valor, categoria, responsavel, mes").eq("mes", mes ?? currentMes()).order("data", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (responsavel) query = query.eq("responsavel", responsavel);
    const { data, error } = await query;
    if (error) return fail(error.message);
    const total = (data ?? []).reduce((s, e) => s + Number(e.valor ?? 0), 0);
    return ok({ mes: mes ?? currentMes(), count: data?.length ?? 0, total, entradas: data ?? [] });
  }
});

// src/lib/mcp/tools/list-gastos.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_gastos_default = defineTool5({
  name: "list_gastos",
  title: "Listar gastos",
  description: "List the signed-in user's expenses (gastos) for a month, optionally filtered by person or category.",
  inputSchema: {
    mes: z5.string().optional().describe('Month name in Portuguese, e.g. "Agosto". Defaults to the current month.'),
    responsavel: z5.string().optional().describe('Person responsible, e.g. "William" or "Andressa".'),
    categoria: z5.string().optional().describe("Expense category filter."),
    limit: z5.number().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mes, responsavel, categoria, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("gastos").select("id, data, descricao, valor, categoria, responsavel, pago, mes").eq("mes", mes ?? currentMes()).order("data", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (responsavel) query = query.eq("responsavel", responsavel);
    if (categoria) query = query.eq("categoria", categoria);
    const { data, error } = await query;
    if (error) return fail(error.message);
    const total = (data ?? []).reduce((s, g) => s + Number(g.valor ?? 0), 0);
    return ok({ mes: mes ?? currentMes(), count: data?.length ?? 0, total, gastos: data ?? [] });
  }
});

// src/lib/mcp/tools/resumo-mensal.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var resumo_mensal_default = defineTool6({
  name: "resumo_mensal",
  title: "Resumo mensal",
  description: "Monthly financial summary for the signed-in user: total income, total expenses, balance, bills paid and pending, and expenses by category.",
  inputSchema: {
    mes: z6.string().optional().describe('Month name in Portuguese, e.g. "Agosto". Defaults to the current month.')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mes }, ctx) => {
    if (!ctx.isAuthenticated()) return fail("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const target = mes ?? currentMes();
    const [entradas, gastos, contas] = await Promise.all([
      supabase.from("entradas").select("valor, responsavel").eq("mes", target),
      supabase.from("gastos").select("valor, categoria, responsavel").eq("mes", target),
      supabase.from("contas").select("valor, pago").eq("mes", target)
    ]);
    const err = entradas.error || gastos.error || contas.error;
    if (err) return fail(err.message);
    const totalEntradas = (entradas.data ?? []).reduce((s, e) => s + Number(e.valor ?? 0), 0);
    const totalGastos = (gastos.data ?? []).reduce((s, g) => s + Number(g.valor ?? 0), 0);
    const porCategoria = {};
    for (const g of gastos.data ?? []) {
      porCategoria[g.categoria] = (porCategoria[g.categoria] ?? 0) + Number(g.valor ?? 0);
    }
    const pagas = (contas.data ?? []).filter((c) => c.pago);
    const pendentes = (contas.data ?? []).filter((c) => !c.pago);
    return ok({
      mes: target,
      moeda: "BRL",
      total_entradas: totalEntradas,
      total_gastos: totalGastos,
      saldo: totalEntradas - totalGastos,
      gastos_por_categoria: porCategoria,
      contas_pagas: pagas.length,
      contas_pendentes: pendentes.length,
      valor_contas_pendentes: pendentes.reduce((s, c) => s + Number(c.valor ?? 0), 0)
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "zfzrajozjxcmktzsypon";
var mcp_default = defineMcp({
  name: "family-finances",
  title: "Family Finances",
  version: "0.1.0",
  instructions: "Tools for the Family Finances app (Portuguese/BRL). Read and record the signed-in user's income (entradas), expenses (gastos) and bills (contas), and get a monthly summary. Months are Portuguese names such as 'Agosto'.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    resumo_mensal_default,
    list_gastos_default,
    add_gasto_default,
    list_entradas_default,
    add_entrada_default,
    list_contas_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
